### ISSUE TITLE
v0.0.3 not working with Refinery

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/docker_igv_js#15]
Hangs on `Please Wait` with `AssertionError()` output to page.

See:
![screen shot 2017-10-25 at 10 29 19 am](https://user-images.githubusercontent.com/5629547/32004326-7cd6f220-b96f-11e7-983e-eac08e40f676.png)

**Comment by mccalluc** [comment]
First problem was a bad key name. Fixed that. Now it loads but tests fail because tracks are not labelled.

**Comment by mccalluc** [comment]
Working now.
